// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: mmopb.proto

#pragma warning disable CS1591, CS0612, CS3021

namespace mmopb
{

    [global::ProtoBuf.ProtoContract()]
    public partial class m_login_s
    {
        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public string name { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public string identifier { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class m_login_c
    {
        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public bool succ { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public string error { get; set; }

        [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
        public p_account_c account { get; set; }

        [global::ProtoBuf.ProtoMember(4, IsRequired = true)]
        public double ticks { get; set; }

        [global::ProtoBuf.ProtoMember(5, TypeName = "mmopb.p_skill")]
        public global::System.Collections.Generic.List<p_skill> skills { get; } = new global::System.Collections.Generic.List<p_skill>();

        [global::ProtoBuf.ProtoMember(6, TypeName = "mmopb.p_item")]
        public global::System.Collections.Generic.List<p_item> items { get; } = new global::System.Collections.Generic.List<p_item>();

        [global::ProtoBuf.ProtoMember(7, TypeName = "mmopb.p_mission")]
        public global::System.Collections.Generic.List<p_mission> missions { get; } = new global::System.Collections.Generic.List<p_mission>();

        [global::ProtoBuf.ProtoMember(8, TypeName = "mmopb.p_server")]
        public global::System.Collections.Generic.List<p_server> servers { get; } = new global::System.Collections.Generic.List<p_server>();

        [global::ProtoBuf.ProtoMember(9, TypeName = "mmopb.r_mapscene")]
        public global::System.Collections.Generic.List<r_mapscene> scenes { get; } = new global::System.Collections.Generic.List<r_mapscene>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class m_error_c
    {
        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public int type { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public string error { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class m_tick_s
    {
        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public long tickc { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class m_tick_c
    {
        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public long ticks { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public long tickc { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class m_server_chose_s
    {
        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public int serverid { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class m_server_chose_c
    {
        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public bool succ { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public string error { get; set; }

        [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
        public int serverid { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class m_avatar_create_s
    {
        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public string name { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public int sex { get; set; }

        [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
        public int pro { get; set; }

        [global::ProtoBuf.ProtoMember(4, IsRequired = true)]
        public int camp { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class m_avatar_create_c
    {
        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public bool succ { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public string error { get; set; }

        [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
        public p_avatar_snapshot snapshot { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class m_avatar_chose_s
    {
        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public double uuid { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class m_avatar_chose_c
    {
        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public bool succ { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public string error { get; set; }

        [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
        public double uuid { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class m_avatar_remove_s
    {
        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public double uuid { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class m_avatar_remove_c
    {
        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public bool succ { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public string error { get; set; }

        [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
        public double uuid { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class m_entity_enter_c
    {
        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public string type { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public double uuid { get; set; }

        [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
        public bool isowner { get; set; }

        [global::ProtoBuf.ProtoMember(4, IsRequired = true)]
        public p_entity entity { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class m_entity_leave_c
    {
        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public double uuid { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class m_chat_s
    {
        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public int type { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public int vip { get; set; }

        [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
        public string uaccount { get; set; }

        [global::ProtoBuf.ProtoMember(4, IsRequired = true)]
        public string uname { get; set; }

        [global::ProtoBuf.ProtoMember(5, IsRequired = true)]
        public string uhead { get; set; }

        [global::ProtoBuf.ProtoMember(6, IsRequired = true)]
        public string smsg { get; set; }

        [global::ProtoBuf.ProtoMember(7, IsRequired = true)]
        public byte[] smic { get; set; }

        [global::ProtoBuf.ProtoMember(8, IsRequired = true)]
        public int smiclen { get; set; }

        [global::ProtoBuf.ProtoMember(9, IsRequired = true)]
        public string toaccount { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class m_chat_c
    {
        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public int type { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public int vip { get; set; }

        [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
        public string uaccount { get; set; }

        [global::ProtoBuf.ProtoMember(4, IsRequired = true)]
        public string uname { get; set; }

        [global::ProtoBuf.ProtoMember(5, IsRequired = true)]
        public string uhead { get; set; }

        [global::ProtoBuf.ProtoMember(6, IsRequired = true)]
        public string cmsg { get; set; }

        [global::ProtoBuf.ProtoMember(7, IsRequired = true)]
        public string cmicid { get; set; }

        [global::ProtoBuf.ProtoMember(8, IsRequired = true)]
        public int cmiclen { get; set; }

        [global::ProtoBuf.ProtoMember(9, IsRequired = true)]
        public double ctime { get; set; }

        [global::ProtoBuf.ProtoMember(10, IsRequired = true)]
        public string toaccount { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class m_mic_s
    {
        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public string micid { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class m_mic_c
    {
        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public string micid { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public byte[] mic { get; set; }

        [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
        public int miclen { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class p_entity_basis
    {
        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public double uuid { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public string name { get; set; }

        [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
        public string account { get; set; }

        [global::ProtoBuf.ProtoMember(4, IsRequired = true)]
        public int serverid { get; set; }

        [global::ProtoBuf.ProtoMember(5, IsRequired = true)]
        public int sex { get; set; }

        [global::ProtoBuf.ProtoMember(6, IsRequired = true)]
        public int pro { get; set; }

        [global::ProtoBuf.ProtoMember(7, IsRequired = true)]
        public int camp { get; set; }

        [global::ProtoBuf.ProtoMember(8, IsRequired = true)]
        public int level { get; set; }

        [global::ProtoBuf.ProtoMember(9, IsRequired = true)]
        public string modelid { get; set; }

        [global::ProtoBuf.ProtoMember(10, IsRequired = true)]
        public float speed { get; set; }

        [global::ProtoBuf.ProtoMember(11, IsRequired = true)]
        public int exp { get; set; }

        [global::ProtoBuf.ProtoMember(12, TypeName = "mmopb.p_item")]
        public global::System.Collections.Generic.List<p_item> equips { get; } = new global::System.Collections.Generic.List<p_item>();

        [global::ProtoBuf.ProtoMember(13, IsRequired = true)]
        public int type { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class p_entity_hmp
    {
        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public double uuid { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public p_hmp hmp { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class p_entity_attr
    {
        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public double uuid { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public p_attr attr { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class p_entity_transform
    {
        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public double uuid { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public p_transform transform { get; set; }

        [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
        public string spacename { get; set; }

        [global::ProtoBuf.ProtoMember(4, IsRequired = true)]
        public string spacepidname { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class p_entity_skillbase
    {
        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public double uuid { get; set; }

        [global::ProtoBuf.ProtoMember(2, TypeName = "mmopb.p_skill_base")]
        public global::System.Collections.Generic.List<p_skill_base> skillbases { get; } = new global::System.Collections.Generic.List<p_skill_base>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class p_entity_skillpassive
    {
        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public double uuid { get; set; }

        [global::ProtoBuf.ProtoMember(2, TypeName = "mmopb.p_skill_base")]
        public global::System.Collections.Generic.List<p_skill_base> skillpassives { get; } = new global::System.Collections.Generic.List<p_skill_base>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class p_entity_skillstatus
    {
        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public double uuid { get; set; }

        [global::ProtoBuf.ProtoMember(2, TypeName = "mmopb.p_skill_base")]
        public global::System.Collections.Generic.List<p_skill_base> skillstatuses { get; } = new global::System.Collections.Generic.List<p_skill_base>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class p_entity
    {
        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public p_entity_basis basis { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public p_entity_hmp hmp { get; set; }

        [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
        public p_entity_attr attr { get; set; }

        [global::ProtoBuf.ProtoMember(4, IsRequired = true)]
        public p_entity_transform transform { get; set; }

        [global::ProtoBuf.ProtoMember(5, IsRequired = true)]
        public p_entity_skillbase skillbases { get; set; }

        [global::ProtoBuf.ProtoMember(6, IsRequired = true)]
        public p_entity_skillpassive skillpassives { get; set; }

        [global::ProtoBuf.ProtoMember(7, IsRequired = true)]
        public p_entity_skillstatus skillstatuses { get; set; }

        [global::ProtoBuf.ProtoMember(8, IsRequired = true)]
        public p_entity_bag bag { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class p_up_basis_levelexp_c
    {
        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public int level { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public int exp { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class p_up_basis_equips_c
    {
        [global::ProtoBuf.ProtoMember(1, Name = @"itemidsremove")]
        public double[] itemidsremoves { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"equipsadded", TypeName = "mmopb.p_item")]
        public global::System.Collections.Generic.List<p_item> equipsaddeds { get; } = new global::System.Collections.Generic.List<p_item>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class p_up_hmp_c
    {
        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public p_hmp hmp { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class p_up_attr_c
    {
        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public p_attr attr { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class p_up_transform_c
    {
        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public p_transform transform { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class p_up_skillbases_c
    {
        [global::ProtoBuf.ProtoMember(1, TypeName = "mmopb.p_skill_base")]
        public global::System.Collections.Generic.List<p_skill_base> skillbases { get; } = new global::System.Collections.Generic.List<p_skill_base>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class p_up_skillpassives_c
    {
        [global::ProtoBuf.ProtoMember(1, TypeName = "mmopb.p_skill_base")]
        public global::System.Collections.Generic.List<p_skill_base> skillpassives { get; } = new global::System.Collections.Generic.List<p_skill_base>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class p_up_skillstatuses_c
    {
        [global::ProtoBuf.ProtoMember(1, TypeName = "mmopb.p_skill_base")]
        public global::System.Collections.Generic.List<p_skill_base> skillstatuses { get; } = new global::System.Collections.Generic.List<p_skill_base>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class p_account_l
    {
        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public string name { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public double uuid_account { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class p_account_b
    {
        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public double uuid { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public string account { get; set; }

        [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
        public double lastseldavataruuid { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public double[] avatars { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class p_account_c
    {
        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public string account { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public double lastseldavataruuid { get; set; }

        [global::ProtoBuf.ProtoMember(3, TypeName = "mmopb.p_avatar_snapshot")]
        public global::System.Collections.Generic.List<p_avatar_snapshot> snapshots { get; } = new global::System.Collections.Generic.List<p_avatar_snapshot>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class p_avatar_snapshot
    {
        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public p_entity_basis avatar { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public p_entity_transform transform { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class p_hmp
    {
        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public double hp { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public double mp { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class p_attr
    {
        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public double health { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public double magic { get; set; }

        [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
        public double attack { get; set; }

        [global::ProtoBuf.ProtoMember(4, IsRequired = true)]
        public double defense { get; set; }

        [global::ProtoBuf.ProtoMember(5, IsRequired = true)]
        public double dodge { get; set; }

        [global::ProtoBuf.ProtoMember(6, IsRequired = true)]
        public double crit { get; set; }

        [global::ProtoBuf.ProtoMember(7, IsRequired = true)]
        public double critdamage { get; set; }

        [global::ProtoBuf.ProtoMember(8, IsRequired = true)]
        public double correctiondamagerate { get; set; }

        [global::ProtoBuf.ProtoMember(9, IsRequired = true)]
        public double correctiondamagevalue { get; set; }

        [global::ProtoBuf.ProtoMember(10, IsRequired = true)]
        public double correctionattackrate { get; set; }

        [global::ProtoBuf.ProtoMember(11, IsRequired = true)]
        public double correctionattackvalue { get; set; }

        [global::ProtoBuf.ProtoMember(12, IsRequired = true)]
        public double correctiontreatmentrate { get; set; }

        [global::ProtoBuf.ProtoMember(13, IsRequired = true)]
        public double correctiontreatmentvalue { get; set; }

        [global::ProtoBuf.ProtoMember(14, IsRequired = true)]
        public double suckbloodrate { get; set; }

        [global::ProtoBuf.ProtoMember(15, IsRequired = true)]
        public double suckbloodvalue { get; set; }

        [global::ProtoBuf.ProtoMember(16, IsRequired = true)]
        public double rebounddamagerate { get; set; }

        [global::ProtoBuf.ProtoMember(17, IsRequired = true)]
        public double rebounddamagevalue { get; set; }

        [global::ProtoBuf.ProtoMember(18, IsRequired = true)]
        public double manashieldoffsetrate { get; set; }

        [global::ProtoBuf.ProtoMember(19, IsRequired = true)]
        public double manashieldconsumevalue { get; set; }

        [global::ProtoBuf.ProtoMember(20, IsRequired = true)]
        public double correctioninjurerate { get; set; }

        [global::ProtoBuf.ProtoMember(21, IsRequired = true)]
        public double correctioninjurevalue { get; set; }

        [global::ProtoBuf.ProtoMember(22, IsRequired = true)]
        public double correctionbetreatmentrate { get; set; }

        [global::ProtoBuf.ProtoMember(23, IsRequired = true)]
        public double correctionbetreatmentvalue { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class p_entity_bag
    {
        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public double uuid { get; set; }

        [global::ProtoBuf.ProtoMember(2, TypeName = "mmopb.p_item")]
        public global::System.Collections.Generic.List<p_item> items { get; } = new global::System.Collections.Generic.List<p_item>();

        [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
        public double diamonds { get; set; }

        [global::ProtoBuf.ProtoMember(4, IsRequired = true)]
        public double gold { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public int[] completedcommonmissionids { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        public int[] completeddailymissionids { get; set; }

        [global::ProtoBuf.ProtoMember(7, TypeName = "mmopb.p_mission_base")]
        public global::System.Collections.Generic.List<p_mission_base> missions { get; } = new global::System.Collections.Generic.List<p_mission_base>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class p_item
    {
        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public double id { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public int typeid { get; set; }

        [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
        public string name { get; set; }

        [global::ProtoBuf.ProtoMember(4, IsRequired = true)]
        public double validitytime { get; set; }

        [global::ProtoBuf.ProtoMember(5, IsRequired = true)]
        public double obtaintime { get; set; }

        [global::ProtoBuf.ProtoMember(6, IsRequired = true)]
        public double expiredtime { get; set; }

        [global::ProtoBuf.ProtoMember(7, IsRequired = true)]
        public double owneruuid { get; set; }

        [global::ProtoBuf.ProtoMember(8, IsRequired = true)]
        public bool binding { get; set; }

        [global::ProtoBuf.ProtoMember(9, IsRequired = true)]
        public int itemtype { get; set; }

        [global::ProtoBuf.ProtoMember(10, IsRequired = true)]
        public int itemsubtype { get; set; }

        [global::ProtoBuf.ProtoMember(11, IsRequired = true)]
        public int bindtype { get; set; }

        [global::ProtoBuf.ProtoMember(12, IsRequired = true)]
        public int quality { get; set; }

        [global::ProtoBuf.ProtoMember(13, TypeName = "mmopb.p_keyvalue")]
        public global::System.Collections.Generic.List<p_keyvalue> userequires { get; } = new global::System.Collections.Generic.List<p_keyvalue>();

        [global::ProtoBuf.ProtoMember(14, TypeName = "mmopb.p_keyvalue")]
        public global::System.Collections.Generic.List<p_keyvalue> useeffects { get; } = new global::System.Collections.Generic.List<p_keyvalue>();

        [global::ProtoBuf.ProtoMember(15, IsRequired = true)]
        public double sellgold { get; set; }

        [global::ProtoBuf.ProtoMember(16, TypeName = "mmopb.p_keyvalue")]
        public global::System.Collections.Generic.List<p_keyvalue> baseattrs { get; } = new global::System.Collections.Generic.List<p_keyvalue>();

        [global::ProtoBuf.ProtoMember(17, TypeName = "mmopb.p_keyvalue")]
        public global::System.Collections.Generic.List<p_keyvalue> addattrs { get; } = new global::System.Collections.Generic.List<p_keyvalue>();

        [global::ProtoBuf.ProtoMember(18, IsRequired = true)]
        public string describe { get; set; }

        [global::ProtoBuf.ProtoMember(19, IsRequired = true)]
        public int num { get; set; }

        [global::ProtoBuf.ProtoMember(20, IsRequired = true)]
        public string icon { get; set; }

        [global::ProtoBuf.ProtoMember(21, IsRequired = true)]
        public string model { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class p_keyvalue
    {
        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public int key { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public int value { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class p_transform
    {
        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public p_vector3 position { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public float direction { get; set; }

        [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
        public float scale { get; set; }

        [global::ProtoBuf.ProtoMember(4, IsRequired = true)]
        public int flag { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class p_vector3
    {
        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public float x { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public float y { get; set; }

        [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
        public float z { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class m_call_b
    {
        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public double uuid { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public byte[] value { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class m_call_c
    {
        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public double uuid { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public byte[] value { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class m_call_m
    {
        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public double uuid { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public byte[] value { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class p_skill
    {
        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public p_skill_base sbase { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public p_skill_attr sattr { get; set; }

        [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
        public p_skill_prepare sprepare { get; set; }

        [global::ProtoBuf.ProtoMember(4, IsRequired = true)]
        public p_skill_cond scond { get; set; }

        [global::ProtoBuf.ProtoMember(5, IsRequired = true)]
        public p_skill_chant schant { get; set; }

        [global::ProtoBuf.ProtoMember(6, IsRequired = true)]
        public p_skill_release srelease { get; set; }

        [global::ProtoBuf.ProtoMember(7, IsRequired = true)]
        public p_skill_finish sfinish { get; set; }

        [global::ProtoBuf.ProtoMember(8, IsRequired = true)]
        public p_skill_continuous scontinuous { get; set; }

        [global::ProtoBuf.ProtoMember(9, IsRequired = true)]
        public p_skill_function sfunction { get; set; }

        [global::ProtoBuf.ProtoMember(10, Name = @"saffects1", TypeName = "mmopb.p_skill_affect")]
        public global::System.Collections.Generic.List<p_skill_affect> saffects1s { get; } = new global::System.Collections.Generic.List<p_skill_affect>();

        [global::ProtoBuf.ProtoMember(11, Name = @"saffects2", TypeName = "mmopb.p_skill_affect")]
        public global::System.Collections.Generic.List<p_skill_affect> saffects2s { get; } = new global::System.Collections.Generic.List<p_skill_affect>();

        [global::ProtoBuf.ProtoMember(12, Name = @"saffects3", TypeName = "mmopb.p_skill_affect")]
        public global::System.Collections.Generic.List<p_skill_affect> saffects3s { get; } = new global::System.Collections.Generic.List<p_skill_affect>();

        [global::ProtoBuf.ProtoMember(13, Name = @"saffects4", TypeName = "mmopb.p_skill_affect")]
        public global::System.Collections.Generic.List<p_skill_affect> saffects4s { get; } = new global::System.Collections.Generic.List<p_skill_affect>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class p_skill_base
    {
        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public int id { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public int statusid { get; set; }

        [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
        public int statuslayers { get; set; }

        [global::ProtoBuf.ProtoMember(4, IsRequired = true)]
        public double statusexpire { get; set; }

        [global::ProtoBuf.ProtoMember(5, IsRequired = true)]
        public double lasttrigger { get; set; }

        [global::ProtoBuf.ProtoMember(6, IsRequired = true)]
        public double srcuuid { get; set; }

        [global::ProtoBuf.ProtoMember(7, IsRequired = true)]
        public int srcproid { get; set; }

        [global::ProtoBuf.ProtoMember(8, IsRequired = true)]
        public int srclevel { get; set; }

        [global::ProtoBuf.ProtoMember(9, IsRequired = true)]
        public p_attr srcattr { get; set; }

        [global::ProtoBuf.ProtoMember(10, IsRequired = true)]
        public double svalue { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class p_skill_attr
    {
        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public int id { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public string name { get; set; }

        [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
        public int type { get; set; }

        [global::ProtoBuf.ProtoMember(4, IsRequired = true)]
        public int subtype { get; set; }

        [global::ProtoBuf.ProtoMember(5, IsRequired = true)]
        public int gaintype { get; set; }

        [global::ProtoBuf.ProtoMember(6, IsRequired = true)]
        public int statusaddtype { get; set; }

        [global::ProtoBuf.ProtoMember(7, IsRequired = true)]
        public double statusduration { get; set; }

        [global::ProtoBuf.ProtoMember(8, IsRequired = true)]
        public double statusinterval { get; set; }

        [global::ProtoBuf.ProtoMember(9, IsRequired = true)]
        public string describe { get; set; }

        [global::ProtoBuf.ProtoMember(10, IsRequired = true)]
        public string icon { get; set; }

        [global::ProtoBuf.ProtoMember(11, IsRequired = true)]
        public string arg0 { get; set; }

        [global::ProtoBuf.ProtoMember(12, IsRequired = true)]
        public string arg1 { get; set; }

        [global::ProtoBuf.ProtoMember(13, IsRequired = true)]
        public string arg2 { get; set; }

        [global::ProtoBuf.ProtoMember(14, IsRequired = true)]
        public string arg3 { get; set; }

        [global::ProtoBuf.ProtoMember(15, IsRequired = true)]
        public string arg4 { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class p_skill_prepare
    {
        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public string prepareaction { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public string prepareeffect { get; set; }

        [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
        public int prepareeffectbind { get; set; }

        [global::ProtoBuf.ProtoMember(4, IsRequired = true)]
        public int prepareeffectbindtype { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class p_skill_cond
    {
        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public int weapontype { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public int aimtype { get; set; }

        [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
        public int aimfixtype { get; set; }

        [global::ProtoBuf.ProtoMember(4, IsRequired = true)]
        public int range { get; set; }

        [global::ProtoBuf.ProtoMember(5, IsRequired = true)]
        public int cdtype { get; set; }

        [global::ProtoBuf.ProtoMember(6, IsRequired = true)]
        public double cdtime { get; set; }

        [global::ProtoBuf.ProtoMember(7, IsRequired = true)]
        public double consumemp { get; set; }

        [global::ProtoBuf.ProtoMember(8, IsRequired = true)]
        public double requirehp { get; set; }

        [global::ProtoBuf.ProtoMember(9, IsRequired = true)]
        public double consumehp { get; set; }

        [global::ProtoBuf.ProtoMember(10, IsRequired = true)]
        public int triggertype { get; set; }

        [global::ProtoBuf.ProtoMember(11, IsRequired = true)]
        public double triggerparam { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class p_skill_chant
    {
        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public double chantduration { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public string chantaction { get; set; }

        [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
        public string chanteffect { get; set; }

        [global::ProtoBuf.ProtoMember(4, IsRequired = true)]
        public int chanteffectbind { get; set; }

        [global::ProtoBuf.ProtoMember(5, IsRequired = true)]
        public int chanteffectbindtype { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class p_skill_release
    {
        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public double releaseeffectplaydelay { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public string releaseaction { get; set; }

        [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
        public string releaseeffect { get; set; }

        [global::ProtoBuf.ProtoMember(4, IsRequired = true)]
        public int releaseeffectbind { get; set; }

        [global::ProtoBuf.ProtoMember(5, IsRequired = true)]
        public int releaseeffectbindtype { get; set; }

        [global::ProtoBuf.ProtoMember(6, IsRequired = true)]
        public double releaseeffecthitdelay { get; set; }

        [global::ProtoBuf.ProtoMember(7, IsRequired = true)]
        public double releaseeffectflyspeed { get; set; }

        [global::ProtoBuf.ProtoMember(8, IsRequired = true)]
        public int releaseeffecthitbind { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class p_skill_continuous
    {
        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public int continuouscount { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public double continuousinterval { get; set; }

        [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
        public double continuouseffectplaydelay { get; set; }

        [global::ProtoBuf.ProtoMember(4, IsRequired = true)]
        public string continuousaction { get; set; }

        [global::ProtoBuf.ProtoMember(5, IsRequired = true)]
        public string continuouseffect { get; set; }

        [global::ProtoBuf.ProtoMember(6, IsRequired = true)]
        public int continuouseffectbind { get; set; }

        [global::ProtoBuf.ProtoMember(7, IsRequired = true)]
        public int continuouseffectbindtype { get; set; }

        [global::ProtoBuf.ProtoMember(8, IsRequired = true)]
        public double continuouseffecthitdelay { get; set; }

        [global::ProtoBuf.ProtoMember(9, IsRequired = true)]
        public double continuouseffectflyspeed { get; set; }

        [global::ProtoBuf.ProtoMember(10, IsRequired = true)]
        public int continuouseffecthitbind { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class p_skill_finish
    {
        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public string finishaction { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class p_skill_function
    {
        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public int functionaimtype { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public double functionrange { get; set; }

        [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
        public int functionrangetype { get; set; }

        [global::ProtoBuf.ProtoMember(4, IsRequired = true)]
        public string functioneffect { get; set; }

        [global::ProtoBuf.ProtoMember(5, IsRequired = true)]
        public int functioneffectbind { get; set; }

        [global::ProtoBuf.ProtoMember(6, IsRequired = true)]
        public int functioneffectbindtype { get; set; }

        [global::ProtoBuf.ProtoMember(7, IsRequired = true)]
        public int functionaimcomputingtime { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class p_skill_affect
    {
        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public int type { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public double param1 { get; set; }

        [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
        public double param2 { get; set; }

        [global::ProtoBuf.ProtoMember(4, IsRequired = true)]
        public double param3 { get; set; }

        [global::ProtoBuf.ProtoMember(5, IsRequired = true)]
        public double param4 { get; set; }

        [global::ProtoBuf.ProtoMember(6, IsRequired = true)]
        public double param5 { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class p_enter_space
    {
        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public string spacename { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public double copyid { get; set; }

        [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
        public p_transform transform { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class p_enter_space_c
    {
        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public bool succ { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public string error { get; set; }

        [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
        public string spacename { get; set; }

        [global::ProtoBuf.ProtoMember(4, IsRequired = true)]
        public p_transform transform { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class p_relive_s
    {
        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public bool backtoborn { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class p_skill_use
    {
        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public int id { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public int aimtype { get; set; }

        [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
        public double taruuid { get; set; }

        [global::ProtoBuf.ProtoMember(4, IsRequired = true)]
        public p_vector3 tarpos { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class p_skill_use_c
    {
        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public bool succ { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public string error { get; set; }

        [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
        public int id { get; set; }

        [global::ProtoBuf.ProtoMember(4, IsRequired = true)]
        public int aimtype { get; set; }

        [global::ProtoBuf.ProtoMember(5, IsRequired = true)]
        public double taruuid { get; set; }

        [global::ProtoBuf.ProtoMember(6, IsRequired = true)]
        public p_vector3 tarpos { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class p_skill_stop
    {
    }

    [global::ProtoBuf.ProtoContract()]
    public partial class p_skill_stop_c
    {
        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public int id { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class p_skill_fire_c
    {
        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public int id { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public int index { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public double[] taruuids { get; set; }

        [global::ProtoBuf.ProtoMember(4, IsRequired = true)]
        public p_vector3 tarpos { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class p_skill_outcome_c
    {
        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public double srcuuid { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public double taruuid { get; set; }

        [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
        public int skillid { get; set; }

        [global::ProtoBuf.ProtoMember(4, IsRequired = true)]
        public int result { get; set; }

        [global::ProtoBuf.ProtoMember(5, IsRequired = true)]
        public double dhp { get; set; }

        [global::ProtoBuf.ProtoMember(6, IsRequired = true)]
        public double dmp { get; set; }

        [global::ProtoBuf.ProtoMember(7, IsRequired = true)]
        public double rhp { get; set; }

        [global::ProtoBuf.ProtoMember(8, IsRequired = true)]
        public double rmp { get; set; }

        [global::ProtoBuf.ProtoMember(9, IsRequired = true)]
        public double vhp { get; set; }

        [global::ProtoBuf.ProtoMember(10, IsRequired = true)]
        public double vmp { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class p_mission
    {
        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public p_mission_base mbase { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public p_mission_attr mattr { get; set; }

        [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
        public p_mission_cond mcond { get; set; }

        [global::ProtoBuf.ProtoMember(4, IsRequired = true)]
        public p_mission_reward mreward { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class p_mission_base
    {
        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public int id { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public int status { get; set; }

        [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
        public double expire { get; set; }

        [global::ProtoBuf.ProtoMember(4, IsRequired = true)]
        public int num1 { get; set; }

        [global::ProtoBuf.ProtoMember(5, IsRequired = true)]
        public int num2 { get; set; }

        [global::ProtoBuf.ProtoMember(6, IsRequired = true)]
        public int num3 { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class p_mission_attr
    {
        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public int id { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public string name { get; set; }

        [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
        public int type { get; set; }

        [global::ProtoBuf.ProtoMember(4, IsRequired = true)]
        public int subtype { get; set; }

        [global::ProtoBuf.ProtoMember(5, IsRequired = true)]
        public double duration { get; set; }

        [global::ProtoBuf.ProtoMember(6, IsRequired = true)]
        public int level { get; set; }

        [global::ProtoBuf.ProtoMember(7, IsRequired = true)]
        public int preid { get; set; }

        [global::ProtoBuf.ProtoMember(8, IsRequired = true)]
        public int camp { get; set; }

        [global::ProtoBuf.ProtoMember(9, IsRequired = true)]
        public int pro { get; set; }

        [global::ProtoBuf.ProtoMember(10, IsRequired = true)]
        public string sdescribe { get; set; }

        [global::ProtoBuf.ProtoMember(11, IsRequired = true)]
        public string edescribe { get; set; }

        [global::ProtoBuf.ProtoMember(12, IsRequired = true)]
        public double npcsid { get; set; }

        [global::ProtoBuf.ProtoMember(13, IsRequired = true)]
        public double npceid { get; set; }

        [global::ProtoBuf.ProtoMember(14, IsRequired = true)]
        public string goaldescribe { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class p_mission_cond
    {
        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public int type1 { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public string desc1 { get; set; }

        [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
        public int param11 { get; set; }

        [global::ProtoBuf.ProtoMember(4, IsRequired = true)]
        public int param12 { get; set; }

        [global::ProtoBuf.ProtoMember(5, IsRequired = true)]
        public int type2 { get; set; }

        [global::ProtoBuf.ProtoMember(6, IsRequired = true)]
        public string desc2 { get; set; }

        [global::ProtoBuf.ProtoMember(7, IsRequired = true)]
        public int param21 { get; set; }

        [global::ProtoBuf.ProtoMember(8, IsRequired = true)]
        public int param22 { get; set; }

        [global::ProtoBuf.ProtoMember(9, IsRequired = true)]
        public int type3 { get; set; }

        [global::ProtoBuf.ProtoMember(10, IsRequired = true)]
        public string desc3 { get; set; }

        [global::ProtoBuf.ProtoMember(11, IsRequired = true)]
        public int param31 { get; set; }

        [global::ProtoBuf.ProtoMember(12, IsRequired = true)]
        public int param32 { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class p_mission_reward
    {
        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public int exp { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public double diamonds { get; set; }

        [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
        public double gold { get; set; }

        [global::ProtoBuf.ProtoMember(4, TypeName = "mmopb.p_keyvalue")]
        public global::System.Collections.Generic.List<p_keyvalue> itemtypeidnums { get; } = new global::System.Collections.Generic.List<p_keyvalue>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class p_up_bag_currency_c
    {
        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public double diamonds { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public double gold { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class p_up_bag_items_c
    {
        [global::ProtoBuf.ProtoMember(1, Name = @"itemidsremove")]
        public double[] itemidsremoves { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"itemsadded", TypeName = "mmopb.p_item")]
        public global::System.Collections.Generic.List<p_item> itemsaddeds { get; } = new global::System.Collections.Generic.List<p_item>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class p_up_bag_missions_c
    {
        [global::ProtoBuf.ProtoMember(1, Name = @"completedcommonmissionidsadded")]
        public int[] completedcommonmissionidsaddeds { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"completeddailymissionidsadded")]
        public int[] completeddailymissionidsaddeds { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"missionidsremove")]
        public int[] missionidsremoves { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"missionsadded", TypeName = "mmopb.p_mission_base")]
        public global::System.Collections.Generic.List<p_mission_base> missionsaddeds { get; } = new global::System.Collections.Generic.List<p_mission_base>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class p_up_bag_mission_c
    {
        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public int id { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public int status { get; set; }

        [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
        public int num1 { get; set; }

        [global::ProtoBuf.ProtoMember(4, IsRequired = true)]
        public int num2 { get; set; }

        [global::ProtoBuf.ProtoMember(5, IsRequired = true)]
        public int num3 { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class p_accept_mission_s
    {
        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public int id { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class p_accept_mission_c
    {
        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public bool succ { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public string error { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class p_submit_completed_mission_s
    {
        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public int id { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class p_submit_completed_mission_c
    {
        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public bool succ { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public string error { get; set; }

        [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
        public int exp { get; set; }

        [global::ProtoBuf.ProtoMember(4, IsRequired = true)]
        public double diamonds { get; set; }

        [global::ProtoBuf.ProtoMember(5, IsRequired = true)]
        public double gold { get; set; }

        [global::ProtoBuf.ProtoMember(6, TypeName = "mmopb.p_item")]
        public global::System.Collections.Generic.List<p_item> items { get; } = new global::System.Collections.Generic.List<p_item>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class p_drop_item
    {
        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public double rate { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public int type { get; set; }

        [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
        public int drop { get; set; }

        [global::ProtoBuf.ProtoMember(4, IsRequired = true)]
        public int num { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class p_drop_package
    {
        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public int id { get; set; }

        [global::ProtoBuf.ProtoMember(2, TypeName = "mmopb.p_drop_item")]
        public global::System.Collections.Generic.List<p_drop_item> items { get; } = new global::System.Collections.Generic.List<p_drop_item>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class p_drop
    {
        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public int mustdrop { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public int maydrop { get; set; }

        [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
        public int questdrop { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class p_equip_load_s
    {
        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public double itemid { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class p_equip_load_c
    {
        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public bool succ { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public string error { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class p_equip_unload_s
    {
        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public double itemid { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class p_equip_unload_c
    {
        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public bool succ { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public string error { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class p_movement_s
    {
        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public p_vector3 position { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public float direction { get; set; }

        [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
        public int flag { get; set; }

        [global::ProtoBuf.ProtoMember(4, IsRequired = true)]
        public float time { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class p_movement_c
    {
        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public p_vector3 position { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public float direction { get; set; }

        [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
        public int flag { get; set; }

        [global::ProtoBuf.ProtoMember(4, IsRequired = true)]
        public float time { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class p_up_ai_c
    {
        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public double owneruuid { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class p_ai_movetoenemy_c
    {
        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public double enemyuuid { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class p_ai_findenemy_c
    {
    }

    [global::ProtoBuf.ProtoContract()]
    public partial class p_ai_findenemy_s
    {
        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public double enemyuuid { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class r_avatar_name
    {
        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public string name { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public double uuid { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class r_counter
    {
        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public string key { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public double value { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class r_bornpoint
    {
        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public string id { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public p_transform transform { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class r_monsterpoint
    {
        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public string id { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public p_transform transform { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class r_npcpoint
    {
        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public string id { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public p_transform transform { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class r_mapmonster
    {
        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public double id { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public string name { get; set; }

        [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
        public int level { get; set; }

        [global::ProtoBuf.ProtoMember(4, IsRequired = true)]
        public string model { get; set; }

        [global::ProtoBuf.ProtoMember(5, IsRequired = true)]
        public double scale { get; set; }

        [global::ProtoBuf.ProtoMember(7, IsRequired = true)]
        public string ai { get; set; }

        [global::ProtoBuf.ProtoMember(8)]
        public int[] skillids { get; set; }

        [global::ProtoBuf.ProtoMember(9, IsRequired = true)]
        public string bornpoint { get; set; }

        [global::ProtoBuf.ProtoMember(10, IsRequired = true)]
        public double relivetime { get; set; }

        [global::ProtoBuf.ProtoMember(11, IsRequired = true)]
        public int type { get; set; }

        [global::ProtoBuf.ProtoMember(12, IsRequired = true)]
        public int sex { get; set; }

        [global::ProtoBuf.ProtoMember(13, IsRequired = true)]
        public int pro { get; set; }

        [global::ProtoBuf.ProtoMember(14, IsRequired = true)]
        public int mustdrop { get; set; }

        [global::ProtoBuf.ProtoMember(15, IsRequired = true)]
        public int maydrop { get; set; }

        [global::ProtoBuf.ProtoMember(16, IsRequired = true)]
        public int questdrop { get; set; }

        [global::ProtoBuf.ProtoMember(17, IsRequired = true)]
        public double golddrop { get; set; }

        [global::ProtoBuf.ProtoMember(18, IsRequired = true)]
        public double expdrop { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class r_mapscene
    {
        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public string mapspace { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public string mapname { get; set; }

        [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
        public string mapscene { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class r_mapwave
    {
        [global::ProtoBuf.ProtoMember(1, TypeName = "mmopb.r_mapmonster")]
        public global::System.Collections.Generic.List<r_mapmonster> monsters { get; } = new global::System.Collections.Generic.List<r_mapmonster>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class r_mapnpc
    {
        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public double id { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public string name { get; set; }

        [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
        public int level { get; set; }

        [global::ProtoBuf.ProtoMember(4, IsRequired = true)]
        public string model { get; set; }

        [global::ProtoBuf.ProtoMember(5, IsRequired = true)]
        public double scale { get; set; }

        [global::ProtoBuf.ProtoMember(7, IsRequired = true)]
        public string ai { get; set; }

        [global::ProtoBuf.ProtoMember(8)]
        public int[] skillids { get; set; }

        [global::ProtoBuf.ProtoMember(9, IsRequired = true)]
        public string bornpoint { get; set; }

        [global::ProtoBuf.ProtoMember(10, IsRequired = true)]
        public double relivetime { get; set; }

        [global::ProtoBuf.ProtoMember(11, IsRequired = true)]
        public int type { get; set; }

        [global::ProtoBuf.ProtoMember(12, IsRequired = true)]
        public int sex { get; set; }

        [global::ProtoBuf.ProtoMember(13, IsRequired = true)]
        public int pro { get; set; }

        [global::ProtoBuf.ProtoMember(14, IsRequired = true)]
        public int mustdrop { get; set; }

        [global::ProtoBuf.ProtoMember(15, IsRequired = true)]
        public int maydrop { get; set; }

        [global::ProtoBuf.ProtoMember(16, IsRequired = true)]
        public int questdrop { get; set; }

        [global::ProtoBuf.ProtoMember(17, IsRequired = true)]
        public double golddrop { get; set; }

        [global::ProtoBuf.ProtoMember(18, IsRequired = true)]
        public double expdrop { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class p_server
    {
        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public int serverid { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public string servername { get; set; }

        [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
        public int serverrealid { get; set; }

        [global::ProtoBuf.ProtoMember(4, IsRequired = true)]
        public int serverstatus { get; set; }

        [global::ProtoBuf.ProtoMember(5, IsRequired = true)]
        public string serverregion { get; set; }

        [global::ProtoBuf.ProtoMember(6, IsRequired = true)]
        public bool serverrecommend { get; set; }

        [global::ProtoBuf.ProtoMember(7, IsRequired = true)]
        public p_time serveropentime { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class p_time
    {
        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public int year { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public int month { get; set; }

        [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
        public int day { get; set; }

        [global::ProtoBuf.ProtoMember(4, IsRequired = true)]
        public int hour { get; set; }

        [global::ProtoBuf.ProtoMember(5, IsRequired = true)]
        public int min { get; set; }

        [global::ProtoBuf.ProtoMember(6, IsRequired = true)]
        public int second { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class p_chat_save
    {
        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public string id { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public string toaccount { get; set; }

        [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
        public m_chat_c chat { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class p_ban_speech
    {
        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public string account { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public double liftbantime { get; set; }

    }

}

public class ILRuntime_mmopb
{
    static ILRuntime_mmopb()
    {

        //Initlize();

    }
    public static void Initlize()
    {
        ProtoBuf.PType.RegisterType("mmopb.p_entity_basis", typeof(mmopb.p_entity_basis));
        ProtoBuf.PType.RegisterType("mmopb.p_account_c", typeof(mmopb.p_account_c));
        ProtoBuf.PType.RegisterType("mmopb.m_login_c", typeof(mmopb.m_login_c));
        ProtoBuf.PType.RegisterType("mmopb.p_skill", typeof(mmopb.p_skill));
        ProtoBuf.PType.RegisterType("mmopb.p_item", typeof(mmopb.p_item));
        ProtoBuf.PType.RegisterType("mmopb.p_mission", typeof(mmopb.p_mission));
        ProtoBuf.PType.RegisterType("mmopb.p_server", typeof(mmopb.p_server));
        ProtoBuf.PType.RegisterType("mmopb.r_mapscene", typeof(mmopb.r_mapscene));
        ProtoBuf.PType.RegisterType("mmopb.p_skill_base", typeof(mmopb.p_skill_base));
        ProtoBuf.PType.RegisterType("mmopb.p_avatar_snapshot", typeof(mmopb.p_avatar_snapshot));
        ProtoBuf.PType.RegisterType("mmopb.p_mission_base", typeof(mmopb.p_mission_base));
        ProtoBuf.PType.RegisterType("mmopb.p_keyvalue", typeof(mmopb.p_keyvalue));
        ProtoBuf.PType.RegisterType("mmopb.p_skill_affect", typeof(mmopb.p_skill_affect));
        ProtoBuf.PType.RegisterType("mmopb.p_drop_item", typeof(mmopb.p_drop_item));
        ProtoBuf.PType.RegisterType("mmopb.r_mapmonster", typeof(mmopb.r_mapmonster));

    }
}

#pragma warning restore CS1591, CS0612, CS3021
